name: Node.js CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests (şimdilik yok)
      run: echo "No tests yet"

    - name: Build Docker image
      run: docker build -t sedabayog/nodejs-devops-app .

    - name: Login to DockerHub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "sedabayog" --password-stdin

    - name: Push Docker image to DockerHub
      run: docker push sedabayog/nodejs-devops-app
