name: Node.js CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Node.js version

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: echo "No tests for now"  # Eğer test yazmadıysan bunu geçebilirsin

    - name: Build Docker image
      run: docker build -t nodejs-devops-app .

    - name: Push Docker image to DockerHub
      run: docker push nodejs-devops-app
